export default {
  LOGOTYPE_ALT: 'NetflixRoulette',
  FILTER_ALL_TAG_CAPTION: 'All',
  SEARCH_TITLE: 'Find your movie',
  SEARCH_PLACEHOLDER: 'What do you want to watch?',
  SEARCH_BUTTON: 'Search',
  SORT_BY_CAPTION: 'Sort by',
  RELEASE_DATE: 'Release date',
  RATING: 'Rating',
  BUTTON_ADD_MOVIE: 'Add movie',
  BUTTON_EDIT: 'Edit',
  BUTTON_DELETE: 'Delete',
  BUTTON_CONFIRM: 'Confirm',
  POPUP_TITLE_EDIT_MOVIE: 'Edit movie',
  POPUP_TITLE_ADD_MOVIE: 'Add movie',
  POPUP_TITLE_DELETE_MOVIE: 'Delete movie',
  POPUP_TEXT_DELETE_MOVIE: 'Are you sure you want to delete this movie?',
};